name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    name: Build & Test (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]  # adicione '21' se quiser testar também no JDK 21

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven   # cache do repositório ~/.m2

      - name: Build & Test (mvn verify)
        run: mvn -B --no-transfer-progress clean verify

      # publica o artefato gerado (ex.: target/*.jar) — útil para baixar e testar localmente
      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.java }}
          path: target/*.*ar
          if-no-files-found: ignore

      # em caso de falha, sobe os relatórios de teste para facilitar debug
      - name: Upload surefire reports on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ matrix.java }}
          path: |
            target/surefire-reports/**
            target/site/surefire-report.html
          if-no-files-found: ignore
